version: '3.7'
services:
  app:
    container_name: react-front-end-app
    build:
      dockerfile: ./docker/react/Dockerfile
    ports:
      - 1111:80
    volumes:
      - '.:/app'
      - '.:/app/node_modules'
    networks:
      - local_network
networks:
  local_network:
    driver: bridge